data_source : https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip

artifacts:
  ARTIFACTS_DIR: artifacts 
  TRAINED_MODEL_DIR: model 
  BASE_MODEL_DIR: base_model # because we are using transfer learning
  BASE_MODEL_NAME: VGG16_base_model.h5 
  UPDATED_BASE_MODEL_NAME: updated_VGG16_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir  # used for all kinds of logs
  TENSORBOARD_ROOT_LOG_DIR: tensor_board_log_dir
  CALLBACKS_DIR: callbacks

source_download_dirs:
  - ../outside_data/dog
  - ../outside_data/cat

local_data_dirs:
  - data/dog
  - data/cat
